### ISSUE TITLE
It doesnt work on Podium Free

### ISSUE THREAD

**Issue by TrinityCodex** [tommitytom/RetroPlug#10]
If i load a rom it freezes while the plugin is completely white. Can still right click.

**Comment by tommitytom** [comment]
Hey there! The emulator itself runs in the audio thread, so if your audio settings are incorrect the emulator will never run and the graphics will not be sent to the UI. Could you double check that your audio settings are correct and that other plugins work fine?

**Comment by TrinityCodex** [comment]
Thank you! i increased the sample rate and it worked!
