### ISSUE TITLE
Any chance also for win32 compilation?

### ISSUE THREAD

**Issue by michaelsjackson** [tommitytom/RetroPlug#11]
Would be cool, using in linux with wine 32-bit, if that would exist. Thanks in advance.

**Comment by tommitytom** [comment]
Due to roundabout the way I have to package Sameboy in to the VST I've struggled to make a stable 32bit build, sadly.  You might have luck with something like this, though I can't say how well it will do in Wine: https://jstuff.wordpress.com/jbridge/

**Comment by michaelsjackson** [comment]
No problem, we do not have to use all instruments. There should be some other similar synths.

**Comment by tommitytom** [comment]
Maybe check out Magical 8bit Plug 2: http://www.ymck.net/en/download/magical8bitplug/

**Comment by michaelsjackson** [comment]
Are they sounding same?  Thanks for the hint, I remember this name, probably I checked it in the past, but can retry it now.
