### ISSUE TITLE
RetroPlug is crashing in FL Studio 20

### ISSUE THREAD

**Issue by siminczak** [tommitytom/RetroPlug#13]
When I try to load a RetroPlug in my FL Studio i receive message:
`The Fruity Wrapper plugin has caused a critical error while loading its state.

It is strongly advised to close the application and restart it, without trying to save your project.
You will find a backup history of your projects in the Backup folder in the browser.

Please contact your plugin's manufacturer about this problem.`

Any ideas what could go wrong?

**Comment by tommitytom** [comment]
This one is gonna be tough to debug as I use it in FL Studio all the time with no issues!  What exact version of FL Studio are you using?  And just to confirm - is it definitely the 64bit version?

**Comment by tommitytom** [comment]
Closing due to lack of response
