### ISSUE TITLE
i cant get lsdj to run in ableton 9 64 bit

### ISSUE THREAD

**Issue by JIMONAH** [tommitytom/RetroPlug#15]
works in renoise on my computer and standalone mode but wont run in ableton live 9 standard 64.bit

**Comment by tommitytom** [comment]
What do you mean by "it won't run"?  Do you get an error?

**Comment by JIMONAH** [comment]
Plugin will load but wont boot sameboy logo or anything after

**Comment by JIMONAH** [comment]
To be more specific i double click to load rom and i just get a white screen after that

**Comment by tommitytom** [comment]
So here's the issue - RetroPlug runs in the audio thread, so if your audio settings are not valid then emulator will never run, and the video feed will never be sent to the UI.  Make sure other plugins run and make sound - once they work, RetroPlug will work too :)

**Comment by JIMONAH** [comment]
Oy my mixer wasnt plugged in , thanks man
