### ISSUE TITLE
retroplug crashes when asio is set as the audio driver

### ISSUE THREAD

**Issue by neonpixii** [tommitytom/RetroPlug#16]
I'm using ableton live 10 lite, retroplug v0.1.0, & sameboy 0.13.6b.  trying to use retroplug causes ableton live 10 to crash, either upon opening retroplug, or sometimes upon trying to load lsdj.

**Comment by neonpixii** [comment]
update: after restarting my computer, the issue seemed to resolve itself

**Comment by neonpixii** [comment]
further update: the problem has returned when i switched my audio driver to ASIO, so i think that this is specifically an issue with retroplug-asio compatibility

**Comment by tommitytom** [comment]
Please try [v0.3.0](https://github.com/tommitytom/RetroPlug/releases/tag/v0.3.0) and see if the problem persists!

**Comment by neonpixii** [comment]
was for some reason, unable to reproduce the problem with the original version.  also works fine w/ v0.3.0

**Comment by tommitytom** [comment]
Okie dokie!  I'm gonna close this as I can't reproduce it - if it happens again feel free to reopen and we can explore the issue some more!
