### ISSUE TITLE
FL Studio reads RetroPlug as an error.

### ISSUE THREAD

**Issue by allforthefuturefree** [tommitytom/RetroPlug#22]
Hello. I've recently downloaded RetroPlug and put it in my VST2 folder, but it won't work and it's detected by FL Studio as an error. Know that I haven't downloaded or done anything else aside from downloading and placing this .DLL file in my VST2 folder. I hope someone can help me. Sorry for any inconvenience.

**Comment by tommitytom** [comment]
Hi there!  Sorry to hear you're having issues.  I use FL Studio myself and it's my main testing platform so I know it works for sure, so let's try and figure out whats going on here.  First thing to check is that you're using the 64bit version of FL Studio - you can find this about by going to `Help -> About` in the menu, and it should say 64bit after the version number.  If you are using the 64bit version, can you confirm the name of the file that you put in your VST folder?

**Comment by allforthefuturefree** [comment]
hi! thanks so much for replying! yes, i confirm that the FL Studio version I'm using is 64bit! and the name of the VST file I put in the VST2 folder is "RetroPlug v0.3.0 (64bit).dll".

**Comment by tommitytom** [comment]
Well that all seems correct!  Does FL Studio give any error information as to why it doesnt load?  Could you possibly screenshot the error for me?

**Comment by allforthefuturefree** [comment]
yeah, absolutely! here are the screenshots

![image](https://user-images.githubusercontent.com/82826998/122235672-4307d300-ce94-11eb-8557-c300ad60ca34.png)

![image](https://user-images.githubusercontent.com/82826998/122235788-5a46c080-ce94-11eb-9eb7-1125e78ebf80.png)

**Comment by tommitytom** [comment]
Ahh, a very useful error message from FL I see :sweat_smile:
OK so next things to try 
- Check if an error log has been written.  This will be written to `C:\Users\USERNAME\AppData\Roaming\RetroPlug\log.txt` (where USERNAME is your current Windows username)
- A few people have described issues when ASIO is set as the audio driver - could you maybe try selecting a different audio drive?
- Does the VST run in any other DAWs on your system?
- Does the standalone build work for you?

**Comment by allforthefuturefree** [comment]
hi, thanks for replying back!

-- an error log hasn't been written. there was also no such directory or folder called RetroPlug or any log TXT file at Roaming, unfortunately.
-- i tried switching the audio driver, but the problem still persists. i think it might not be related in my case.
-- the VST isn't even recognized or read by another DAW i have installed in my PC called Studio One 5.
-- the standalone version doesn't work either, it displays a message that says that a .DLL file is missing called like this: 
![image](https://user-images.githubusercontent.com/82826998/122310958-85a6cb00-cee7-11eb-86e8-3540f7a3ac85.png)

perhaps i had to install something? i haven't installed anything at all aside from this plugin by putting it in the VST2 folder. perhaps i have to download or install something else?

**Comment by tommitytom** [comment]
Aha!  Looks like you need the latest Visual C++ redistributable from Microsoft: https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

Direct link: https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by allforthefuturefree** [comment]
OMG, YES! IT WORKED! THANK YOU SO MUCH, DUDE! YOU'RE THE BEST! I'm glad you helped me! thank you for your time, dude! everything's working as it should now! have a good one!

**Comment by tommitytom** [comment]
Glad I could help.  And thanks for taking the time to make a bug request!  I've added this info to the readme file.  Enjoy :)
