### ISSUE TITLE
Req: Add the option to start/stop on DAW Transport Start/Stop

### ISSUE THREAD

**Issue by peterswimm** [tommitytom/RetroPlug#3]
There should be a menu toggle that if enabled, will send start button clicks when transport starts and again when it is turned off. This will prevent the requirement that LSDJ transport is armed before starting daw transport.

**Comment by tommitytom** [comment]
I like this.  What should the option be called?  I was thinking `Auto Play` or `Sync Transport`

**Comment by peterswimm** [comment]
Probably the first one is more accurate unless you are gonna be really ambitious and try to map daw song position to the equivalent lsdj chain (although I think if you want to do that, you'd use the midimap aboy mode)

**Comment by tommitytom** [comment]
Added in [v0.0.2](https://github.com/tommitytom/RetroPlug/releases/tag/v0.0.2).

**Comment by peterswimm** [comment]
Yay! This rocks.

**Comment by tommitytom** [comment]
I actually uploaded the wrong binaries to the release (whoops!).  Proper versions are up now in case you already downloaded!
